version: '2'
services:
  app:
    build: ./containers/app
    networks:
      - frontend
      - backend
    volumes:
      - .:/var/www/html
    ports:
      - "80:80"

  db:
    build: ./containers/db
    networks:
      - backend
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - "3306:3306"

networks:
  frontend:
  backend:

volumes:
  mysql-data:
